[package]
name = "nuvi"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "Nuvi"
path = "src/main.rs"

[dependencies]
async-channel = "2.5"
async-process = "2.5"
async-std = "1.13"
async-trait = "0.1"
compact_str = "0.10.0"
gpui = { version = "=0.2.2", default-features = false, features = ["font-kit"] }
nvim-rs = { version = "0.9.2", features = ["use_async-std"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
